1. read supported funding model platforms
2. open money form
3. click max or enter '999'
4. click send

<img src="https://img.shields.io/liberapay/receives/kilitary.svg?logo=liberapay">

github: [kilitary]
liberapay: [kilitary] 
custom (horses entry): ['https://vk.com/agent1348']

all under still not defaced by me (working):

<img src="https://img.shields.io/liberapay/patrons/kilitary.svg?logo=liberapay">

patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username


<img src="https://img.shields.io/liberapay/goal/kilitary.svg?logo=liberapay">
